CREATE TABLE IF NOT EXISTS lusha_recruiters (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    lusha_contact_id VARCHAR(64) NOT NULL,
    lusha_request_id VARCHAR(64) NULL,
    full_name VARCHAR(255) NULL,
    first_name VARCHAR(120) NULL,
    last_name VARCHAR(120) NULL,
    job_title VARCHAR(255) NULL,
    company_id BIGINT NULL,
    company_name VARCHAR(255) NULL,
    company_fqdn VARCHAR(255) NULL,
    linkedin_url VARCHAR(512) NULL,
    twitter_url VARCHAR(512) NULL,
    city VARCHAR(120) NULL,
    state VARCHAR(120) NULL,
    country VARCHAR(120) NULL,
    country_iso2 CHAR(2) NULL,
    continent VARCHAR(80) NULL,
    is_shown BOOLEAN NULL,
    is_enrich_success BOOLEAN NULL,
    linkedin_followers_count INT NULL,
    linkedin_connections_count INT NULL,
    has_emails BOOLEAN NULL,
    has_work_email BOOLEAN NULL,
    has_private_email BOOLEAN NULL,
    has_phones BOOLEAN NULL,
    has_mobile_phone BOOLEAN NULL,
    has_direct_phone BOOLEAN NULL,
    has_company_employees_count BOOLEAN NULL,
    has_company_revenue BOOLEAN NULL,
    has_company_main_industry BOOLEAN NULL,
    has_company_sub_industry BOOLEAN NULL,
    has_company_funding BOOLEAN NULL,
    has_company_intent BOOLEAN NULL,
    has_company_technologies BOOLEAN NULL,
    has_department BOOLEAN NULL,
    has_seniority BOOLEAN NULL,
    has_contact_location BOOLEAN NULL,
    has_social_link BOOLEAN NULL,
    main_industry VARCHAR(180) NULL,
    sub_industry VARCHAR(180) NULL,
    signal_types_json JSON NULL,
    departments_json JSON NULL,
    seniority_json JSON NULL,
    email_addresses_json JSON NULL,
    phone_numbers_json JSON NULL,
    linkedin_certifications_json JSON NULL,
    linkedin_courses_json JSON NULL,
    linkedin_awards_json JSON NULL,
    linkedin_skills_json JSON NULL,
    company_funding_json JSON NULL,
    company_intent_json JSON NULL,
    company_technologies_json JSON NULL,
    company_revenue_range_json JSON NULL,
    raw_lusha_search_json JSON NULL,
    raw_lusha_enrich_json JSON NULL,
    source_app VARCHAR(100) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_lusha_contact_id (lusha_contact_id),
    UNIQUE KEY uq_lusha_recruiters_linkedin_url (linkedin_url),
    KEY idx_lusha_recruiters_company_name (company_name),
    KEY idx_lusha_recruiters_country_iso2 (country_iso2),
    KEY idx_lusha_recruiters_updated_at (updated_at)
);

CREATE TABLE IF NOT EXISTS recruiter_conversations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    recruiter_id BIGINT UNSIGNED NOT NULL,
    channel ENUM('linkedin', 'email', 'other') NOT NULL DEFAULT 'linkedin',
    thread_external_id VARCHAR(255) NULL,
    campaign_name VARCHAR(160) NULL,
    status ENUM('active', 'paused', 'closed', 'failed') NOT NULL DEFAULT 'active',
    conversation_context_json JSON NULL,
    last_message_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_recruiter_conversations_recruiter_channel (recruiter_id, channel),
    KEY idx_recruiter_conversations_thread_external_id (thread_external_id),
    KEY idx_recruiter_conversations_status_last_message (status, last_message_at),
    CONSTRAINT fk_recruiter_conversations_recruiter_id
        FOREIGN KEY (recruiter_id) REFERENCES lusha_recruiters(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    conversation_id BIGINT UNSIGNED NOT NULL,
    message_external_id VARCHAR(255) NULL,
    sender_type ENUM('recruiter', 'bot', 'human_agent', 'system') NOT NULL,
    direction ENUM('inbound', 'outbound', 'internal') NOT NULL,
    message_type ENUM('text', 'note', 'template', 'system_event') NOT NULL DEFAULT 'text',
    content_text TEXT NULL,
    message_context_json JSON NULL,
    context_source VARCHAR(120) NULL,
    parent_message_id BIGINT UNSIGNED NULL,
    sent_at DATETIME NULL,
    received_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_conversation_messages_conversation_created (conversation_id, created_at),
    KEY idx_conversation_messages_sender_direction (sender_type, direction),
    KEY idx_conversation_messages_context_source (context_source),
    KEY idx_conversation_messages_message_external_id (message_external_id),
    CONSTRAINT fk_conversation_messages_conversation_id
        FOREIGN KEY (conversation_id) REFERENCES recruiter_conversations(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_conversation_messages_parent_message_id
        FOREIGN KEY (parent_message_id) REFERENCES conversation_messages(id)
        ON DELETE SET NULL
);
